name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.6','3.7','3.8', '3.9']
        experimental: [false]
        include:
          - os: ubuntu-20.04
            python-version: '3.10-dev'
            experimental: true
    steps:
    - name: Cancel previous
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ github.token }}
    
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system packages
      run: |
        sudo apt-get install g++
        sudo apt-get install cmake
        sudo apt-get install bison
        sudo apt-get install flex
        sudo apt-get install python3.7

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Tests
      if: matrix.python-version != '3.10-dev'
      run: python build_scripts/ci_script.py

    - name: Run Tests for python 3.10
      if: matrix.python-version == '3.10-dev'
      run: python build_scripts/ci_script.py || exit 0

  test-aarch64:
    name: "Test aarch64"
    strategy:
     # matrix:
      #  pyver: [cp36-cp36m, cp37-cp37m, cp38-cp38, cp39-cp39]
      fail-fast: false
    runs-on: ubuntu-20.04
   # env:
    #  py: /opt/python/${{ matrix.pyver }}/bin/python
     # img: quay.io/pypa/manylinux2014_aarch64
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        git submodule init
        git submodule update
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: Install dependencies and test
      run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
            arm64v8/ubuntu \
            bash -exc 'apt update && \
            uname -m && \
            apt-get install sudo && \
            apt install software-properties-common -y && \
            sudo add-apt-repository ppa:deadsnakes/ppa && \
            sudo apt install python3.7 -y && \
            python3.7 -m pip install --upgrade pip && \
            #sudo apt-get -y install python3.7 && \
            python3.7 -m pip install virtualenv && python3.7 -m venv .env && \
            source .env/bin/activate && \
            #sudo apt-get -y install python-is-python3 && \
            uname -m && \
            sudo apt-get -y install g++ && \
            sudo apt-get -y install cmake && \
            sudo apt-get -y install bison && \
            sudo apt-get -y install flex && \
            #sudo apt-get -y install python3-pip && \
            #yum -y install gcc-c++ cmake bison flex python3-devel && \
            python3 --version && \
            python3 -m pip install -r requirements.txt && \
            python3 build_scripts/ci_script.py && \
            deavtivate'
